### ISSUE TITLE
Use templating?

### ISSUE THREAD

**Issue by DavidLGoldberg** [atom/notifications#1]
This looks really nice so far.  I peaked at the code and was surprised to see no templating.

I haven't got around to using custom elements in atom.  Is there an example of declarative / templating with markup?  Rather building up the markup dynamically via code that is?

Just curious!

**Comment by mark-hahn** [comment]
Please see the specification for the second version of my `space-pen` replacement, now called `space-brush`.   I feel it meets all the needs discussed so far.  It has all the capabilities of polymer and react (minus DOM clone) and keeps the space-pen easy-to-use DSL syntax.

https://github.com/mark-hahn/space-brush

I would be forever grateful if anyone would read it and give comments.  

**Note:** I may be crazy, but if the Atom team were to design agree-upon specs for a template/platform solution to be recommended for Atom packages, I would be happy to do the implementation.  I would be like a free contractor. (grin)   It doesn't have to be space-brush at all, but keeping much of the space-brush philosophy would be nice.  Note that I bring a lot of Atom package development experience to the table.
