### ISSUE TITLE
Make the plugin less annoying

### ISSUE THREAD

**Issue by janmarek** [atom/notifications#104]
This happens to me several times in a minute. And I don't care about it at all.

![snimek obrazovky 2015-12-03 v 17 15 37](https://cloud.githubusercontent.com/assets/150257/11566162/87a70668-99e1-11e5-8958-9a620c8f8829.png)

There are ways how to improve user experience with this plugin:

- option to show notifications in status bar only: https://github.com/atom/notifications/issues/14
- option to disable repeated errors: https://github.com/atom/notifications/issues/88
- option to disable notices (not reported yet)
- option to disable it for buggy addons: https://github.com/atom/notifications/issues/90
- do not place it notifications over tabs: https://github.com/atom/notifications/issues/86

Current situation is insane.

**Comment by lee-dohm** [comment]
> option to disable notices (not reported yet)

If you want to completely disable notifications, you can disable the notifications package in the Settings View.

Since, as you pointed out, all the other user experience enhancements are already reported, I'm going to close this as a duplicate.
