### ISSUE TITLE
Replace user profile

### ISSUE THREAD

**Issue by 50Wliu** [atom/notifications#120]
Notifications should replace the user profile with something generic to reduce the number of duplicates (a great example of this is atom/atom#9559 - just keep scrolling down) ~~as well as to protect user privacy~~*.  @dirk-thomas referenced 30 duplicates...we're at 133 and counting, and atom/atom#10774 is at 36 right now :grimacing:.

For example, `/Users/username/Atom.app/whatever` could be replaced with `~/Atom.app/whatever`, and `C:\Users\username\stuff` could become `%USERPROFILE%\stuff`.

This has the potential to remove some important information such as non-ASCII characters in the username, but such cases are generally rare.  If needed we could add an extra `Username: ` line when a username is detected and the user opts in to it.

Refs #113.

\* Not currently feasible yet due to how Windows stack traces are formatted, so only the title gets replaced.  Perhaps later.

**Comment by lee-dohm** [comment]
If we want to match by Issue title, exceptions that occur on multiple platforms will all need their paths to be normalized to a single standard. Otherwise, `%USERPROFILE%\stuff` still won't match `~/stuff`.

**Comment by 50Wliu** [comment]
I was thinking about doing that, but wouldn't `~\stuff` still not match `~/stuff`?  In order for the issue titles to completely match notifications would also need to standardize path separators.

**Comment by lee-dohm** [comment]
@50Wliu I would agree with normalizing the path separators too so that `%USERPROFILE%\stuff` becomes `~/stuff`.
