### ISSUE TITLE
Enable .addError to handle Error-Objects

### ISSUE THREAD

**Issue by florianb** [atom/notifications#122]
This would enable just adding an Error-Notification with an Error and probably saves some developers some seldom Exceptions complaining about the wrong data type of the messages.

As an nifty Addon, the Notification could treat `err.stack` as the detail-option.

🍰 ☕

**Comment by lee-dohm** [comment]
I suspect this belongs on https://github.com/atom/atom since that is where the code for the `atom.notifications` object resides. Would you mind reopening it there?

**Comment by florianb** [comment]
@lee-dohm: of course - sorry for the misplacement.. 😩
