### ISSUE TITLE
Remove animation when closing

### ISSUE THREAD

**Issue by simurai** [atom/notifications#123]
Carried over from https://github.com/atom/one-dark-ui/issues/132

> @j127 It's disorienting to have error messages pulsate needlessly before flying off the screen. They should just disappear without distracting the user. It's too much visual input when trying to solve bugs with add-ons.

> If a user needs to see something, then a small amount of animation can bring attention to something, but when you're dismissing an error message, you're already done with it at that point and it should disappear inconspicuously.

**Comment by simurai** [comment]
Ok, in #124, there is still a short animation, just because it's more consistent when auto-closing. But there no bounce and a shorter duration.

**Comment by j127** [comment]
Thanks! Fading out is tolerable. It's the wiggle that really gets to me when I'm concentrating on small details.
