### ISSUE TITLE
Are the stack, description, and buttons options safe to use?

### ISSUE THREAD

**Issue by Gawdl3y** [atom/notifications#126]
Are the `stack`, `description`, and `buttons` options on `Notification`s safe to use in packages? Are they stable? These are all definitely useful options for the notifications.
Currently, there is absolutely no documentation on these options AFAIK. The only place they are referenced currently is in the [`NotificationElement`](https://github.com/atom/notifications/blob/master/lib/notification-element.coffee) class. There is nothing about them in the [`Notification`](https://github.com/atom/atom/blob/master/src/notification.coffee) class/documentation or [`NotificationManager`](https://github.com/atom/atom/blob/master/src/notification-manager.coffee) class/documentation.

I've already made use of `buttons` in my [build-papyrus](https://github.com/Gawdl3y/build-papyrus) package, but I'd like to ensure this will be safe to do in the future.

**Comment by 50Wliu** [comment]
There is a PR open that documents them at atom/atom#11942.

**Comment by lee-dohm** [comment]
Since the linked PR was merged, I'm going to close this. What was documented in that PR is what we're comfortable with supporting.
