### ISSUE TITLE
Uncaught TypeError: Cannot read property 'nodeName' of null

### ISSUE THREAD

**Issue by RoberCastro** [atom/notifications#152]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [notifications](https://github.com/atom/notifications) package 0.66.2

### Stack Trace

Uncaught TypeError: Cannot read property 'nodeName' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/command-logger.js:81

TypeError: Cannot read property 'nodeName' of null
    at CommandLogger.module.exports.CommandLogger.logCommand (/app.asar/node_modules/notifications/lib/command-logger.js:81:38)
    at /app.asar/node_modules/notifications/lib/command-logger.js:33:24
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:240:20)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at /packages/git-plus/lib/git-plus.coffee:225:27)
    at HTMLDivElement.dispatch (/packages/git-plus/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/git-plus/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
```

### Non-Core Packages

```
atom-ternjs 0.18.2 
atom-typescript 11.0.1 
auto-detect-indentation 1.3.0 
auto-indent-file 0.2.0 
autoclose-html 0.23.0 
busy-signal 1.3.0 
emmet 2.4.3 
git-plus 7.4.0 
highlight-selected 0.13.1 
intentions 1.1.2 
laravel 0.7.1 
linter 2.1.2 
linter-eslint 8.1.5 
linter-sass-lint 1.7.4 
linter-ui-default 1.2.2 
open-in-browser 0.5.0 
open-in-browsers 0.0.19 
platformio-ide-terminal 2.5.0 
```

**Comment by rsese** [comment]
Thanks for contributing!

Based on the stack trace, I think this might be caused by the [git-plus](https://github.com/akonwi/git-plus) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

**Comment by alexd-conf** [comment]
I got the same error on a similar platform: can confirm that it occurred while using 'git-plus' functionality.

**Comment by guillochon** [comment]
I'm still getting this issue, even after a restart.

**Comment by h4km** [comment]
how to fix it?

**Comment by rsese** [comment]
@guillochon @h4km - can you post steps to reproduce and confirm if it's reproducible in safe mode?

**Comment by alexd-conf** [comment]
IIRC the context of my (our?) issue was when I, from Atom, 'Git Plus: checkout remote $remoteRepo' where the remote had the same branch name as the origin ('master'). I performed the comparable git command in CLI and it was fine.

@guillochon @h4km does this sound familiar?

**Comment by black-snow** [comment]
@rsese In my case I just clicked on `master` in the bottom right corner (provided by git-plus).

**Comment by eatobin** [comment]
to @rsese:  ditto @black-snow.

**Comment by 50Wliu** [comment]
Please file an issue on the git-plus repository.  This happened once before with a different package and is due to a coding error on the package's part.
