### ISSUE TITLE
Uncaught Error: Pane has been destroyed

### ISSUE THREAD

**Issue by sdimmick** [atom/notifications#154]
[Enter steps to reproduce:]

I had a few files open in Atom, switched to a branch where some of the files didn't exist, then closed all the open files.

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [notifications](https://github.com/atom/notifications) package 0.66.2

### Stack Trace

Uncaught Error: Pane has been destroyed

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:847

Error: Pane has been destroyed
    at Pane.module.exports.Pane.activate (/app.asar/src/pane.js:847:15)
    at /app.asar/node_modules/notifications/lib/notification-element.js:298:40)
    at /app.asar/node_modules/notifications/lib/notification-element.js:256:19)
    at /app.asar/node_modules/notifications/lib/notification-element.js:59:26
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Notification.module.exports.Notification.dismiss (/app.asar/src/notification.js:79:27)
    at /app.asar/node_modules/notifications/lib/notification-element.js:260:25)
    at /app.asar/node_modules/notifications/lib/notification-element.js:149:26)
```

### Commands

```
     -0:43.9.0 tabs:close-all-tabs (li.texteditor.tab.sortable.active.modified.right-clicked)
     -0:09.8.0 core:cancel (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack.remove)
     -0:04.0 fuzzy-finder:toggle-file-finder (atom-pane.pane)
     -0:02.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.22 
atom-html-preview 0.1.22 
busy-signal 1.3.0 
editorconfig 2.2.2 
intentions 1.1.2 
language-cjsx 0.3.0 
linter 2.1.4 
linter-eslint 8.1.6 
linter-js-standard 3.9.0 
linter-ui-default 1.2.3 
standard-formatter 2.8.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* Did you have multiple panes open?
* Is the error is reproducible?
* If reproducible, do you see the error in safe mode (atom --safe)?

**Comment by sdimmick** [comment]
@rsese I haven't been able to reproduce it yet. Sorry about that - I should have confirmed it was actually reproducible before filing the report.

I had two panes open (split left / right).

**Comment by rsese** [comment]
No problem at all @sdimmick thanks for confirming :v:   If you end up being able to reproduce, please let us know.

**Comment by rsese** [comment]
Seems like you haven't hit this problem again so we'll go ahead and close for now, thanks again for reporting.

**Comment by sdimmick** [comment]
@rsese yup, it only happened that one time. Thanks for following up!
