### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by twifty** [atom/notifications#184]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When using the built in `ResizeObserver` 'Uncaught TypeError' errors are being logged to the console. The problem occurs when an element being observed is resized during the 'onResize' handler, which causes the observer to enter an endless loop.

Looking into the [code](https://github.com/atom/notifications/blob/93bc60249d314adf0fa4d248b5d390d5d32c4422/lib/main.coffee#L22) I can see that the `originalError` is being passed as 'null'.

### Steps to Reproduce

Use the built in `ResizeObserver` to observe an element, from within the handler resize the same element (cause an endless loop).

**Expected behavior:** 

The actual error to be displayed.

**Actual behavior:**

Error handler is not checking for null/undefined, masking the real problem.

**Reproduces how often:** 

100%

### Versions

v1.24 (Though the problem exists in master, linked above)

**Comment by rsese** [comment]
Thanks for the report!   Would it be possible to share a some code that reproduces the behavior you're describing?

**Comment by lee-dohm** [comment]
Thank you for your submission!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/17020. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

Or if you know exactly where the bug in the code is, we would be happy to review a well-written pull request to address the problem. Let us know if we can help out :+1:
