### ISSUE TITLE
Increase Notification Duration 

### ISSUE THREAD

**Issue by VickyAgravat** [atom/notifications#186]
Add Option to Set Notification Duration Time.

Some times large message can not read in sort duration.

**Comment by rsese** [comment]
This has been added in https://github.com/atom/notifications/pull/182 and will be available in a future release.

There's also a notifications log available as of at least 1.26 (currently in beta) - from the command palette, the command is `Notifications: Toggle Log`.  You'll be able to see past notifications there even if you miss them as they popup.
