### ISSUE TITLE
Display Issues in atom-nightly

### ISSUE THREAD

**Issue by akonwi** [atom/notifications#195]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Attempted to reproduce the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
'info' type notifications created without an `icon` option don't display properly.

### Steps to Reproduce

1. open atom-nightly
2. open the dev tools
3. from the console run `atom.notifications.addInfo('foo', {dismissable: true, icon: 'plus'})`
4. observe the correctly displayed notification with the 'plus' icon
5. from the dev console run `atom.notifications.addInfo('foo', {dismissable: true})`
6. the new notification will look distorted. you can hover over the icon and it will expand as well

**Expected behavior:** [What you expect to happen]

I expect to clearly see two notifications

**Actual behavior:** [What actually happens]

![image](https://user-images.githubusercontent.com/2013804/42909930-aa6f17c4-8ab3-11e8-9be4-c1aab7606f1b.png)

**Reproduces how often:** [What percentage of the time does it reproduce?]

every time

### Versions

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.30.0-nightly9
python 2.7.10
git 2.15.2

macOS 10.13.6

### Additional Information

I'm unable to reproduce this in safe mode. I am using the `one dark` ui and syntax themes

**Comment by Aerijo** [comment]
> I'm unable to reproduce this in safe mode

That indicates a package you have is (at least partly) responsible. Narrowing it down should help with identifying the cause.

**Comment by akonwi** [comment]
okay this is weird. now i can't reproduce it at all. i'll close this and re-open it if i see it again and am able to determine what might be causing it
