### ISSUE TITLE
Add notification log viewer panel

### ISSUE THREAD

**Issue by benogle** [atom/notifications#29]
- [x] Add logs panel
- [x] Style logs
- [ ] Populate logs with real notifications
- [ ] Make error logs expandable

**Comment by simurai** [comment]
Added a logs panel to the `sm-logs` branch. Currently with just some sample markup.

![screen shot 2015-02-24 at 10 24 12 pm](https://cloud.githubusercontent.com/assets/378023/6350325/2684fbe0-bc76-11e4-9c4f-e6ce69c8bcd9.png)

All items would be collapsed. And you could click on the errors to expand them and see more infos. Not sure how to add the real content? I guess it could be the same as the notification, but there are also things not needed. Like the close buttons.

**Comment by benogle** [comment]
Lookin awesome :+1: as usual.

Would it be possible to reuse the same notification element for these items, and just style them differently? That might be crazy as the buttons would probably be off to the right of the notification, where they are currently below everything in their own container. I'm definitely down to change the logic in NotificationElement to make this easier.

**Comment by simurai** [comment]
Yes, I changed it to also use the `<atom-notification>` elements for the logs. They're now scoped to `atom-notifications atom-notification` and `.notifications-logs atom-notification` so the styling is separate, but they share the same markup. The not used close buttons are just hidden.

![screen shot 2015-02-25 at 11 28 59 am](https://cloud.githubusercontent.com/assets/378023/6363906/812981a8-bce2-11e4-993b-f475de2d253f.png)

The logs would need some open/collapse logic to see the `detail` and `meta` when clicked. But I guess they stay open inside `atom-notifications`.

Also, populating the logs should probably only happen once you open the panel?

**Comment by simurai** [comment]
@benogle Do you feel like taking over a bit? Added a todo at the top.. probably lots more needed.

**Comment by Goddard** [comment]
Any way to disable the pop ups?

**Comment by benogle** [comment]
@Goddard which ones are bothering you?

**Comment by Goddard** [comment]
I am using remote-sync and it has deprecation messages.

**Comment by benogle** [comment]
So are those deprecations popping up notifications? Or are they showing in the status bar?

**Comment by Goddard** [comment]
showed a message once on launch and then just showing in the status bar.

**Comment by benogle** [comment]
@Goddard what did the message say on launch?

**Comment by mark-hahn** [comment]
What will show when we are editing?  I'd like just a small icon in the status bar that can be clicked to bring up this panel.  The icon can have a count next to it.  

See https://discuss.atom.io/t/can-i-turn-off-the-notifications/17117/16.

**Comment by benogle** [comment]
@mark-hahn that was the plan: to show an icon in the status bar with a count.

**Comment by batjko** [comment]
Will the items in the panel just be a history of notifications, or can people add log output there as well?
I ask because people sometimes ask whether there is a way to create log out, other than the dev tools console.

**Comment by benogle** [comment]
The intention at this time is just to have a historical view of notifications that happen. We _could_ add some kind of logging interface. I mean, I think what people want in that case is something like https://github.com/tcarlsen/atom-message-panel. Right?

**Comment by batjko** [comment]
Yes exactly. 
If @simurai's design above is used here, I'd certainly prefer it though,

**Comment by baelter** [comment]
is this happening?

**Comment by simurai** [comment]
@baelter No imminent plans. 😞  But the `sm-logs` branch is still there and I also still like the idea.

Another option would be that the log is not expandable, but if you click on a log item, it would open the notification where you can see all the details. That's probably easier to implement and less to maintain?

![screen shot 2016-11-22 at 10 32 29 am](https://cloud.githubusercontent.com/assets/378023/20507678/85460af6-b09f-11e6-93df-9a82df59a383.png)

**Comment by jordwalke** [comment]
This was such a great idea/design. The stock Atom notifications are very intrusive. This design solves many of those problems. Great work on coming up with the plan. I hope someone takes over.

**Comment by baelter** [comment]
All I am looking for is a log of past notifications. Or that notifications don't fade on hover would also do. Atom doesn't care that I am reading...

**Comment by tgrrr** [comment]
@benogle +1 for icon with count.

This looks great. What's needed to develop this?

**Comment by Blackclaws** [comment]
Why is this not a thing yet? The current way notifications are handled is horrible. If I have a plugin that errors out I would like that to be logged for my convenience not sprawled across the screen.

**Comment by UziTech** [comment]
I created a pull request #164 that adds `sm-logs` and actually works with real notifications.

I tried implementing @simurai's plan to show the notification regularly when it is clicked in the log, but it would take a lot of reworking how the notifications are removed.

My pull request does expand a notification if it is clicked.

**Comment by UziTech** [comment]
I got it working to re-show the notifications when they are clicked on in the log 🎉 🌟

**Comment by 50Wliu** [comment]
Implemented in #164.
