### ISSUE TITLE
Set optional timeout for notifications

### ISSUE THREAD

**Issue by 50Wliu** [atom/notifications#35]
I poked around a bit in the source code and couldn't find this, so:
Could an option be added so that notifications will automatically disappear after a set amount of time?  I realize that the Notifications API is still experimental but this is for a little side project that I'm doing that probably won't get published anytime soon.

Possible use-case:  Coding->trigger keybinding that does stuff and displays a notification->keep coding but the notification never disappears until you manually close it :(

**Comment by benogle** [comment]
When `dismissible` is false on the notification, it will hide after some time (5sec?). Right now, most of them are created with `dismissible: true`. I will feel more comfortable having more of them not be `dismissible` when there is a log of notifications the user can see later.

**Comment by 50Wliu** [comment]
Well I feel stupid now.  I was setting `dismissable: true` instead of `dismissible`...
Thanks.
