### ISSUE TITLE
option to turn off markdown

### ISSUE THREAD

**Issue by ruv** [atom/notifications#45]
I think that it could be good to involve the new option to specify that a message text is not in Markdown but merely a plain text. Something like Content-Type in HTTP. And check `if @model.getOptions().contenttype == 'text/plain'`. If `contenttype` is not set it should be treated as default  `text/markdown`
So, in case of content type is "text/plain" it should make escape for HTML instead of translate Markdown near [the code](/atom/notifications/blob/99eb09787dbb8a1c9668473cd5cab6ae6e75705b/lib/notification-element.coffee#L67):

```
notificationContainer.innerHTML = marked(@model.getMessage())
```

It will allow to avoid escaping for Markdown in plain text messages.
See also atom/snippets#117

**Comment by benogle** [comment]
Yeah, definitely seems reasonable

**Comment by lee-dohm** [comment]
Thanks for the suggestion.

While this may be a reasonable feature to add at some point, it isn't something that we want to maintain long term. Every feature added means more work down the road and we don't believe that this would be useful in enough cases to support a completely separate content type (let alone the implications of what if people used content types other than `text/plain`).

Thanks again for sharing your ideas!
