### ISSUE TITLE
Misalignment in the notification popup?

### ISSUE THREAD

**Issue by lee-dohm** [atom/notifications#57]
![napkin 05-02-15 12 09 07 pm](https://cloud.githubusercontent.com/assets/1038121/7442383/09237c52-f0c4-11e4-9508-fb7042d0268d.png)

This is using Atom v0.197.0-bc0e5ad running Mac OS X 10.10.3 on my Retina iMac.

/cc @simurai

**Comment by simurai** [comment]
This seems to be only an issue in the One themes. Closing it here in favor of https://github.com/atom/one-dark-ui/issues/66
