### ISSUE TITLE
`clear` is not documented

### ISSUE THREAD

**Issue by noseglid** [atom/notifications#73]
I've recently started using the build in notifications in Atom in [my build package](https://atom.io/packages/build). I have some specs which trigger the error message I use. Problem is that they persist between specs. I see that you call `atom.notifications.clear()`. Maybe this should be documented so I can use it safely and find it easily.

**Comment by izuzak** [comment]
@benogle `NotificationManager.clear` [isn't listed as a public API currently](https://github.com/atom/atom/blob/f55c95bd01b652d5b22bf789391770e8aa694c43/src/notification-manager.coffee#L86-L91) -- would we consider changing that?

**Comment by damieng** [comment]
I don't think we want to encourage package authors to clear notifications that have been created by other packages.
