### ISSUE TITLE
[question] How does this package know what package Fatal Errors come from?

### ISSUE THREAD

**Issue by alexbuzzbee** [atom/notifications#80]
I'm attempting to develop a package which replaces the normal dialog for Fatal Error notifications, but I need to know what package threw a Fatal Error. It's obviously possible to know this, (as this package does so), but I can't figure out how.

**Comment by benogle** [comment]
via [this method](https://github.com/atom/notifications/blob/e78cf641f76a504f5df5a77cab2f3ce8a499f199/lib/notification-issue.coffee#L174) It should probably be pulled out into a library as a few packages need this functionality.
