### ISSUE TITLE
Wrap whole words in notification detail

### ISSUE THREAD

**Issue by mnquintana** [atom/notifications#84]
_From @mnquintana on May 22, 2015 19:45_

Refs https://github.com/atom/settings-view/pull/509

Extremely minor, but I noticed that the notification detail where package names are listed wraps characters instead of whole words, which can have some interesting results with package names:

![screen shot 2015-05-22 at 3 41 11 pm](https://cloud.githubusercontent.com/assets/823545/7778455/7690a78a-0099-11e5-95d9-b7f0b4abeec2.png)

`hellcheck`

_Copied from original issue: atom/settings-view#517_

**Comment by mnquintana** [comment]
_From @benogle on July 7, 2015 0:58_

This notification doesnt exist anymore. Closing. I suppose this could be an issue with notification's detail field.

**Comment by rageandqq** [comment]
+1! is this going to be merged in any time soon?
