### ISSUE TITLE
Notification cover tab bar.

### ISSUE THREAD

**Issue by gandm** [atom/notifications#86]
Notifications cover the tab bar making it difficult to change tabs whilst an error exists. Can notifications be placed lower down.

**Comment by emileber** [comment]
I would really like to choose from which corner the notifications can appear. Making them appear from the lower right corner would solve this issue and we could still view code since it's possible to scroll past the end of file content.

**Comment by simurai** [comment]
Not sure if/when this gets addressed, but in the meantime, you could temporarily add this to your `styles.less`:

```less
atom-notifications {
    top: 50px; // move notifications down a bit
}
```

![screen shot 2016-03-10 at 4 24 57 pm](https://cloud.githubusercontent.com/assets/378023/13662291/b6d81cf4-e6dc-11e5-896f-93cc40f715f8.png)

**Comment by emileber** [comment]
Thanks @simurai

**Comment by emacstheviking** [comment]
Awesome. I should have read further before complaining!

**Comment by damieng** [comment]
@simurai Do we want to do something like this in the default themes or just have this as a workaround for people who run into it?

**Comment by emileber** [comment]
I would say **it should be the default**, or move the notifications to the bottom.

**Comment by simurai** [comment]
Yeah, for the bundled themes we can move it down a bit. Moving to the bottom is also problematic because it will cover things like find-and-replace.

**Comment by damieng** [comment]
Fixed in 4c2b349bd70e121de9900fdc68789e2997ed7861

**Comment by simurai** [comment]
@damieng With `35px` the tabs will still be covered when using a custom title bar:

![screen shot 2017-01-11 at 1 40 56 pm](https://cloud.githubusercontent.com/assets/378023/21835858/c28a7614-d803-11e6-9983-9b6594b7168e.png)

But maybe ok, since you can still click the tabs behind.

**Comment by damieng** [comment]
Yeah we can't compensate for everything a theme/person might do without restructing where notifications live in the DOM which would probably open a whole other can of worms.

**Comment by emileber** [comment]
At least it's not completely covered anymore.
