### ISSUE TITLE
issues with large stack traces create http get urls that are too long

### ISSUE THREAD

**Issue by devoncarew** [atom/notifications#89]
For issues with very large stack traces, attempting to report them to github will return `414 Request-URI Too Large` errors. There should be a limit placed on the max stack size that is reported.

https://github.com/atom/notifications/blob/a6f7bc203f30c164bc0ef40b14604e032803372d/lib/notification-issue.coffee#L57

**Comment by 50Wliu** [comment]
Can you please move this to atom/notifications?
Also, Windows already uses the shortened `git.io` URL, so this should be pretty easy to fix.

**Comment by mnquintana** [comment]
@50Wliu This is on atom/notifications :see_no_evil:

**Comment by 50Wliu** [comment]
Wow, I'm totally not on my game today :frowning:.

**Comment by rtack** [comment]
seems this hasn't been solved yet. should it be reopened?

**Comment by Ben3eeE** [comment]
@rtack There is an open issue: https://github.com/atom/notifications/issues/129
