### ISSUE TITLE
Failed to load/activate package bug should be filed on package not Atom?

### ISSUE THREAD

**Issue by lee-dohm** [atom/notifications#98]
I'm seeing a lot of these:

* https://github.com/atom/atom/issues/9416
* https://github.com/atom/atom/issues/9410
* https://github.com/atom/atom/issues/9396
* https://github.com/atom/atom/issues/9394
* https://github.com/atom/atom/issues/9364
* https://github.com/atom/atom/issues/9350
* ...

Most likely the issue is with the code in the package, not Atom, yes? Even though the stack trace doesn't mention the package ... perhaps for this specific message we should file it on the package first?

**Comment by 50Wliu** [comment]
Some are, like Icehunter/language-jsx#5.  It seems more like the Notifications package is bugged (#66).
